# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MovieList' do
  use_frameworks! 
    pod 'RxSwift', '~> 6.5'
    pod 'RxCocoa', '~> 6.5'
    pod 'Swinject'
    pod 'SwinjectStoryboard'
    pod 'Alamofire', '~> 5.6'
    pod 'SwiftMessages', '~> 9.0'
  end

  target 'MovieListTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MovieListUITests' do
    # Pods for testing
  end
